FROM maven:3.9.6-amazoncorretto-21 AS build
WORKDIR /app
COPY pom.xml .
COPY src ./src
RUN mvn clean package -DskipTests

FROM amazoncorretto:21
WORKDIR /app
COPY --from=build /app/target/central-base-station-1.0-SNAPSHOT.jar app.jar
# ENTRYPOINT ["java", "-jar", "app.jar"]
ENTRYPOINT ["java", \
  "-XX:+FlightRecorder", \
  "-XX:StartFlightRecording=duration=60s,filename=/data/recording.jfr,settings=profile", \
  "-jar", "app.jar"]